/**
 * T-507 commit D: the Mods copy `storybloq setup-skill` installs for Claude
 * Code function hooks, and the version-marker refresh keeps current.
 *
 * WHAT IS COPIED. The plugin's manifest with `skills` dropped (the copy
 * carries no skill directory; /story is installed separately), the hooks
 * runtime files (every hooks/*.ts that is not a kit test, plus hooks.json),
 * and a GENERATED hooks/install.ts whose `resolveStorybloqBin()` answers the
 * absolute path of the global storybloq binary. A Mod runs under whatever
 * PATH the client has, which is not the shell's, so the bare name the
 * repository copy answers is not enough there.
 *
 * WHERE. ~/.claude/skills/storybloq/, beside the /story skill at
 * ~/.claude/skills/story/. The client loads it with
 * `claude --plugin-dir ~/.claude/skills/storybloq` under
 * CLAUDE_CODE_ENABLE_FUNCTION_HOOKS=1; both Mods stay off until their
 * userConfig option is set.
 *
 * HOW. The whole tree is staged beside the destination and swapped in with
 * the same atomic swap the skill copy uses (`copyDirRecursive`), so a
 * failure while staging leaves the previous copy untouched and no partial
 * copy is ever loadable.
 */

import { existsSync, readFileSync } from "node:fs";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";

export const MODS_DIR_NAME = "storybloq";

/** The Mods copy's directory: ~/.claude/skills/storybloq/. */
export function modsDir(): string {
  return join(homedir(), ".claude", "skills", MODS_DIR_NAME);
}

export const MODS_DISPLAY_PATH = "~/.claude/skills/storybloq/";

/**
 * Resolves the bundled plugin directory, in either layout:
 *   - Bundled (npm): dist/cli.js, plugin at <pkg>/plugins/storybloq
 *   - Source (dev):  src/core/mods-install.ts, plugin at <pkg>/plugins/storybloq
 */
export function resolvePluginSourceDir(): string {
  const thisDir = dirname(fileURLToPath(import.meta.url));
  const bundled = join(thisDir, "..", "plugins", MODS_DIR_NAME);
  if (existsSync(join(bundled, "hooks", "mod.ts"))) return bundled;
  const source = join(thisDir, "..", "..", "plugins", MODS_DIR_NAME);
  if (existsSync(join(source, "hooks", "mod.ts"))) return source;
  throw new Error(`Cannot find the bundled plugin source. Checked:\n  ${bundled}\n  ${source}`);
}

/** True when a Mods copy is installed (its hooks module exists), so a refresh has something to refresh. */
export function modsInstalled(dir: string = modsDir()): boolean {
  return existsSync(join(dir, "hooks", "mod.ts"));
}

/**
 * The generated hooks/install.ts. A string literal, JSON-escaped, so a path
 * with a quote, a backslash or a space still parses; the bare name when no
 * global binary could be resolved at install time.
 */
export function renderInstallModule(bin: string | null): string {
  const answer = bin === null ? "storybloq" : bin;
  const how = bin === null
    ? " * No global storybloq binary could be resolved when this copy was written,\n" +
      " * so this answers the bare name and the host resolves it on its PATH. A\n" +
      " * later `storybloq setup-skill`, or the version-marker refresh, replaces it."
    : " * The absolute path of the global storybloq binary as resolved when this\n" +
      " * copy was written. The version-marker refresh re-resolves it when the\n" +
      " * binary moves (an nvm switch), so this copy follows the CLI.";
  return (
    "/**\n" +
    " * GENERATED by `storybloq setup-skill` (T-507). Do not edit: the next\n" +
    " * refresh overwrites it.\n" +
    " *\n" +
    `${how}\n` +
    " */\n" +
    "export function resolveStorybloqBin(): string {\n" +
    `  return ${JSON.stringify(answer)};\n` +
    "}\n"
  );
}

export interface InstallModsOptions {
  /** The resolved global binary, or null when none could be resolved. */
  readonly bin: string | null;
  /** The plugin directory to copy from; the bundled one by default. */
  readonly sourceDir?: string;
  /** Where to install; `modsDir()` by default. */
  readonly destDir?: string;
}

export interface InstallModsResult {
  readonly dir: string;
  readonly bin: string | null;
  /** Paths written, relative to `dir`. */
  readonly written: readonly string[];
}

const REQUIRED_HOOK_FILES = ["hooks.json", "mod.ts"];

/**
 * Installs (or replaces) the Mods copy. Stages the whole tree beside the
 * destination, then swaps it in atomically; throws before touching the
 * destination when the source is missing or incomplete.
 */
export async function installMods(options: InstallModsOptions): Promise<InstallModsResult> {
  const dir = options.destDir ?? modsDir();
  const sourceDir = options.sourceDir ?? resolvePluginSourceDir();
  const manifestPath = join(sourceDir, ".claude-plugin", "plugin.json");
  if (!existsSync(manifestPath) || !existsSync(join(sourceDir, "hooks"))) {
    throw new Error(`Mods plugin source not found at ${sourceDir}`);
  }
  for (const name of REQUIRED_HOOK_FILES) {
    if (!existsSync(join(sourceDir, "hooks", name))) {
      throw new Error(`Mods plugin source at ${sourceDir} is incomplete: hooks/${name} is missing`);
    }
  }

  const manifest = JSON.parse(readFileSync(manifestPath, "utf-8")) as Record<string, unknown>;
  delete manifest["skills"];

  const runtimeFiles = (await readdir(join(sourceDir, "hooks")))
    .filter((name) => (name.endsWith(".ts") && !name.endsWith(".test.ts")) || name === "hooks.json")
    .filter((name) => name !== "install.ts")
    .sort();

  const stage = `${dir}.stage-${process.pid}`;
  await rm(stage, { recursive: true, force: true });
  const written: string[] = [];
  try {
    await mkdir(join(stage, ".claude-plugin"), { recursive: true });
    await mkdir(join(stage, "hooks"), { recursive: true });
    await writeFile(join(stage, ".claude-plugin", "plugin.json"), JSON.stringify(manifest, null, 2) + "\n", "utf-8");
    written.push(".claude-plugin/plugin.json");
    for (const name of runtimeFiles) {
      await writeFile(join(stage, "hooks", name), await readFile(join(sourceDir, "hooks", name)));
      written.push(`hooks/${name}`);
    }
    await writeFile(join(stage, "hooks", "install.ts"), renderInstallModule(options.bin), "utf-8");
    written.push("hooks/install.ts");

    const { copyDirRecursive } = await import("../cli/commands/setup-skill.js");
    await copyDirRecursive(stage, dir);
  } finally {
    await rm(stage, { recursive: true, force: true });
  }
  return { dir, bin: options.bin, written };
}
